### ISSUE TITLE
build crashes on android with bluetooth gamepad unless nil check is added

### ISSUE THREAD

**Issue by jojomickymack** [ponywolf/joykey#1]
I had to wrap lines 63 to 65 of joykey.lua in a if then end like so to avoid a crash caused by 'table index is nil' on android
```lua
if event.keyName then
  event.phase = "down"
  eventCache[event.keyName] = true
  Runtime:dispatchEvent( event )
end
```
I also added one to the 'key' function in the main.lua file where event.keyName is logged (line 53).

Note: I had to apply the same change on line 64 to 'stickerknight' as well to avoid crashes when using the gamepad on android as well, now gamepads are working on both platforms.

**Comment by superqix** [comment]
Fixed this in the lastest update
